dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

install:
  - pip install pytest

before_script:
  - "python setup.py install"

script:
  - pytest tests/test_miscutils.py
